### ISSUE TITLE
js: converting BN to JS number in filterForOpenOrdersFromSlab

### ISSUE THREAD

**Issue by mihneacalugaru** [Bonfida/dex-v4#102]
Hello,

The `filterForOpenOrdersFromSlab` from `market.ts` tries to convert the `price` and `size` from `BN` to JS number (`toNumber()`) that is capable of only storing 53 bits.

In some cases, this will not work. For example, if you have a `quoteCurrencyMint` with 6 decimals and a `quoteCurrencyMultiplier` of 10000 (10^4) and you place an order of UI value of 1000000 (+ with the adjustments of 10^6 because of the 6 decimals and the 10^4 `quoteCurrencyMultiplier` to get it to raw unscaled form) will fail to be converted `toNumber()` because it will exceed the 53 bits JS limit.

![image](https://user-images.githubusercontent.com/54309756/220305614-d8819c01-fb71-465f-815b-d03550abb43d.png)

I can go ahead and create a PR with the simple change of removing the `toNumber()`, but I don't want to create breaking changes that could affect any other devs using this library.

Maybe we should add an optional parameter that will tell whether we want the `price` and `size` to stay `BN` or to be converted `toNumber()` and set the default value to be the conversion `toNumber()` in order to not break anything for the lib consumers?

Also, this will be in the spirit of consistency with the `_parseSlab` function that returns the `price` and the `size` as `BN`.

**Comment by dr497** [comment]
Hi @mihneacalugaru! Thanks for the catch!

I think the optional parameter is a good approach to avoid breaking anything. It would be very helpful if you could open a PR for this 🙏

**Comment by mihneacalugaru** [comment]
Would https://github.com/Bonfida/dex-v4/pull/103/files work?

**Comment by dr497** [comment]
The PR has been merged and the package published to NPM - thanks for your contribution!

**Comment by mihneacalugaru** [comment]
Hello @dr497, sorry for the friction, I noticed that I forgot to implement the option to pass that optional parameter from upstream methods to the one using it.

I also created #104. Would you be so kind to look over it and if it's okay with you to merge it and publish a new npm version?

**Comment by dr497** [comment]
Good catch! Merged and published!
