### ISSUE TITLE
BPF build of the program error

### ISSUE THREAD

**Issue by mihneacalugaru** [Bonfida/dex-v4#105]
Hello,

I am trying to produce a **.so** file that can be deployed on the devnet in order for me to experiment with the code.

Reading the documentation, I understood that I should use the `cargo build-bpf` to produce the .so file by giving as parameters the path to the .toml file (the manifest path) and an output directory for the result.

After some tries, I am getting this:
![image](https://user-images.githubusercontent.com/54309756/221868091-685f012d-0b4b-446e-b21a-61dcb97f2671.png)

Can you help me figure out why I get this?

Also, if you can walk me through the steps to produce a .so deployable from the `program` in this repo I would greatly appreciate it!

Thanks a lot!

L.E.: After a cargo update in `program` I get:
![image](https://user-images.githubusercontent.com/54309756/221873247-02bbcfdb-b688-43f8-be4e-074e53b122aa.png)

**Comment by dr497** [comment]
Have you modified your `Cargo.lock`?

**Comment by mihneacalugaru** [comment]
@dr497 , no.

The following screenshot will show the steps to reproduce since cloning the repo:

![image](https://user-images.githubusercontent.com/54309756/221876448-92f0922e-0c86-46d3-9cc9-fb4c4847067a.png)

**Comment by ellttBen** [comment]
@mihneacalugaru Can you try and cd into the `program` directory before running `cargo build-bpf`? My suspicion is that it's looking for a Cargo.lock in your current directory, and tries to build it itself.

**Comment by mihneacalugaru** [comment]
Hi @ellttBen,

Tried with no luck:

![image](https://user-images.githubusercontent.com/54309756/221887653-54183e1d-ae69-4109-97f5-6dd2ff153f06.png)

**Comment by ellttBen** [comment]
Hey @mihneacalugaru, do you also get this issue on the `alpha` branch?

**Comment by mihneacalugaru** [comment]
@ellttBen, I have a quick question: you said here (https://github.com/Bonfida/dex-v4/issues/98#issuecomment-1387694661) that you have deployed the program.

I assume you built the `program` with `cargo build-bpf`, got the .so file and deployed it using `solana program deploy` with the path to that .so. Is this right?

How did you manage to make it build? Am I missing something? Can you help me with the steps to build this program and deploy it? I would appreciate a lot!

**Comment by ellttBen** [comment]
At the time I just ran `cargo build-bpf` in the `program` folder and didn't run into any issue.
Currently the main branch is broken, probably due to a dependency update in a past commit (we tested the bindings but not building the program itself, ie the bpf target). This issue is currently fixed in the `alpha` branch.
However, even on the main branch, I can't reproduce the error you're seeing. What is really confusing to me is that your error indicates that cargo is attempting to resolve the dependency versions itself instead of using the existing `Cargo.lock`.
Can you try switching to the `alpha` branch and then, in the `program` folder, running `cargo build-bpf` without any arguments? If this fails can you try `cargo build-bpf --frozen`?

**Comment by ellttBen** [comment]
Also, your screenshot indicates that you are running a pretty old version of the Solana tool suite, an upgrade might be a good step forward towards solving the issue

**Comment by mihneacalugaru** [comment]
@ellttBen, ok, so I did the following: (also, note that I am on a Windows machine)

1. Updated the Solana Tool Suite

![image](https://user-images.githubusercontent.com/54309756/222006362-e5c2dc6e-c9ab-48ba-86ed-c40a81cf1c7b.png)

I am at `1.15.2`.

Also, these are my `rustc` and `rustup` versions, also updated:

![image](https://user-images.githubusercontent.com/54309756/222006512-7aeceda8-92d5-4ba8-8767-83eb0d8b2574.png)

2. I ran `cargo-build-bpf` in the `alpha` branch and now I get:

![image](https://user-images.githubusercontent.com/54309756/222006792-938e4e1a-001e-4d38-be78-ee210ac72550.png)
![image](https://user-images.githubusercontent.com/54309756/222006835-05600729-d4db-4f2c-833e-47e845bd744a.png)

3. if I run `cargo-build-**sbf**`, which is supposed to replace the deprecated `cargo-build-bpf` I get:
 
![image](https://user-images.githubusercontent.com/54309756/222007124-7cabc40f-d365-4555-ab33-9f067b4a09b9.png)

So, still that issue with `blake3 v1.3.3`, but also those other 2 errors above it.

4. I don't understand why I can't use `cargo build-bpf` (the version without the `-` between `cargo` and `build`)

![image](https://user-images.githubusercontent.com/54309756/222007894-f6bcd31a-753c-4c86-9f30-ded3f126bb27.png)

I am only able to run the version with dashes all around (`cargo-build-bpf` or `cargo-build-sbf`), which I believe gets actually called by `cargo build-bpf/sbf` that I can't access.

I uninstalled rust and installed it again and I also brought the Solana Tool Suite to the latest version.

Any ideas? :(

**Comment by ellttBen** [comment]
From what I can gather it seems your dev/build environment is completely broken. There are a few possible issues here, but ultimately I think you're just going have to tinker. I personally don't have any experience making the toolchain work with Windows, so it might be easier to switch to a Linux vm.
A couple ideas to look into in the mean time :
- The cargo error message might mean that you have two different versions of rust installed, one through rustup, one not
- It's okay to use bpf and not sbf for now
- Maybe update your build tools (gcc, etc.), those are packaged by Microsoft
- Use docker to build
- There's a known issue with the latest version of Rust being unsupported, so you might want to switch to an earlier version (`rustup default 1.66.1`)
- Maybe try and get some help on the Solana stack exchange, as this is unrelated to `dex-v4`

**Comment by mihneacalugaru** [comment]
@ellttBen, I ran it on my WSL (Windows Subsystem for Linux) with a clean environment and it worked.

Might be something with my Windows environment. It seems that it tries to use the Visual Studio installed MASM to target the x64 code and that one doesn't execute successfully.

Anyway, it works on a clean Linux env. Will close it.

Thanks!
