### ISSUE TITLE
SPL token account owner not validated on market creation

### ISSUE THREAD

**Issue by armaniferrante** [Bonfida/dex-v4#14]
The `AccountInfo` owner (not the data owner) field is not validated here https://github.com/Bonfida/dex-v3/blob/main/program/src/processor/create_market.rs#L109, allowing one to hijack a given market address for PDA markets that don't do this validation them self, since subsequent instructions might simply not work if accounts *not* owned by the spl token program are used as vaults.

**Comment by Lcchy** [comment]
This has now been added https://github.com/Bonfida/dex-v4/blob/3858b583a0610fe22c1ff4c62f72b3bacd916e2e/program/src/processor/create_market.rs#L69
