### ISSUE TITLE
Client order ID functionality is missing

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/dex-v4#36]
Apparently client order IDs are really important to market makers and this new version of the serum dex doesn't appear to implement them

**Comment by armaniferrante** [comment]
@jarry-xiao what do you think?

**Comment by jarry-xiao** [comment]
What do you mean by client order ID's here? I do see a list of `order_id`'s present in the `UserAccount` struct. I imagine that this is sufficient information because you can look up the order in the corresponding Slab tree, and the Slab tree will in turn have a `callback_info` pointer that identifies the user making the trade

**Comment by dr497** [comment]
Not sure I follow either, `OrderSummary` returned by the AOB contains an order ID

**Comment by Henry-E** [comment]
Client order id is a functionality provided by the old serum dex and pretty
much all cex apis where you can specify your own order id to refer to an
order by later. It allows market makers to send orders with their client
order id and refer to it at a later time using that same id without having
to look up what order id was given by the program.

Dex v3 had the option to place new orders with a client order id and to
cancel orders using the same client order id.

A market maker told me that when trading they never use the order id
assigned by the exchange in their code, only their own client order IDs. So
it seems like a pretty important functionality.

**Comment by Henry-E** [comment]
[cancel_order_by_client_id_v2](https://github.com/project-serum/serum-dex/blob/master/dex/src/state.rs#L2722-L2746)
Where the client order ids are stored in the [open orders account](https://github.com/project-serum/serum-dex/blob/4258756cf7fc6ab240c855c08ea54bd813c4e9ac/dex/src/state.rs#L603) in parallel to the regular order ids

**Comment by jarry-xiao** [comment]
It sounds like something that can be implemented fairly easily, though I'm not entirely sure of how the `client_id` would be passed in (through `new_order`?). Definitely seems like a good feature to support users cancelling by a custom id if that makes it easier for them to migrate over existing systems. Granted the indirection stage of mapping client orders to exchange orders could definitely be managed by off-chain client.
