### ISSUE TITLE
Suggestion: Don't error if 0 events consumed

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/dex-v4#37]
https://github.com/Bonfida/dex-v4/blob/661ba307c98c2fa567ef552bd27bdd2f64b1b24c/program/src/processor/consume_events.rs#L112-L115

In Serum V3 many users / market makers submit `consume events` instructions along with other instructions in order to ensure that any cancelled or matched orders have been processed and the freed assets can be used. However, it's not possible to know ahead of time whether or not the event queue has already been cleared. Therefore it's a bad idea to explicitly error if no events are consumed. It would be better for the function to silently fail or return.

**Comment by dr497** [comment]
Returning an error is great because it prevents you from sending a tx that will fail by using a preflight check but I agree in some cases it might be useful.

The solution should be to add an optional param `allow_no_op` in order to have both behaviors.

**Comment by Henry-E** [comment]
Surely the default should be to allow 0 events to be consumed without the function erroring. What scenarios are there in which you would want an error to return if no events are consumed? If there was an optional argument for the opposite, to `disallow_no_op` then that would be fine.

**Comment by Henry-E** [comment]
> Returning an error is great because it prevents you from sending a tx that will fail by using a preflight check but I agree in some cases it might be useful.

I totally get this now. It is useful for crankers to have the default be to return an error so they don't waste a transaction. And to just have a special option to prevent failure in the case of market makers or whomever passing in consume events with other functions in a transaction that they don't want cancelled if there are no events to consume.

**Comment by Lcchy** [comment]
Thanks for the input, we added a parameter to the instruction that can control this behavior.
