### ISSUE TITLE
Log out market address along with order summary

### ISSUE THREAD

**Issue by Dassy23** [Bonfida/dex-v4#40]
I think it would be beneficial to log out the market address with the order summary in the tx. When using the logs to index trade data it is important to know where the order is coming from. Here is an example order summary log from testnet. 

https://solscan.io/tx/a7szfpDtYRQ7e1Hnqf7TAV4LBZcMHd2VLMvyF19qL23zqDn32JBr8YMdmkGH6NGPUAh1U1aT4bCv8CFEj5Q45vK?cluster=devnet

**Comment by dr497** [comment]
You can already access the market address by looking at the accounts of the instruction https://github.com/Bonfida/dex-v4/blob/main/program/src/processor/new_order.rs#L82

**Comment by Dassy23** [comment]
perfect! thank you ser
