### ISSUE TITLE
QOL Changes to bindings functions and market functions

### ISSUE THREAD

**Issue by jhlx** [Bonfida/dex-v4#71]
* In `createMarket`, metadataAccount should be optional
* In `makePlaceOrderTransaction`, clientOrderId should be optional
* Change `tickSize` parameter to be a `number` rather than BN **or** change `minBaseOrderSize` to be a `BN` rather than a `number`, for consistency
* Document what the unit scaling is for `tickSize` and `minBaseOrderSize` (e.g. should you pass in `uiAmount`, `uiAmount * 2 ** 32`, `uiAmount * 10 ** quoteDecimals`, or something else?)

**Comment by dr497** [comment]
https://github.com/Bonfida/dex-v4/pull/75
