### ISSUE TITLE
BN error thrown when trying to load market

### ISSUE THREAD

**Issue by petrucioinica99** [Bonfida/dex-v4#87]
I am trying to connect to a market that I created, but the Market.load function crashesh with the following message:
Error: Number can only safely store up to 53 bits

The stack trace points to the computeUiPrice function in the utils file. The tick size I put for the market was new BN(100) and the minBaseOrderSize  new BN(1).

The connection url is: https://api.devnet.solana.com/
The market address: 2v3gEUKpBWRircVW6PXG1Q8bd8C3g5WrYbRNfpoxHRT1
The program id: HEHEVQNZMTmjUt3CUKdddqHWa4dtXqA9QUsi7QptCCHj 
The mint address: AF5DV1Ngx5BZ8pSPE1XCUvpoRCeMjHRsH2AFqu3zyCLe

**Comment by dr497** [comment]
Hi! 

I believe the overflow issue you are running into is due to an incorrect `quoteCurrencyMultiplier` parameter (https://github.com/Bonfida/dex-v4/blob/main/program/src/state.rs#L83). Your current market has a `quoteCurrencyMultiplier` set to 1 while it should be something like `10^6`

**Comment by petrucioinica99** [comment]
That was the issue, indeed!

I created a new market with a quoteCurrencyMultiplier of 10^9 and it no longer crashed when trying to load it. Thank you very much, you saved me there!

On a side note, is there an expected date for when v4 goes into mainnet? It feels like a better developer experience to work with v4 and I'd like to go directly with v4 for the project I am working on.
