### ISSUE TITLE
No orders returning in loadOrdersForOwner

### ISSUE THREAD

**Issue by petrucioinica99** [Bonfida/dex-v4#90]
When trying to get a wallet's orders for a market, the function always returns an empty array, even though the wallet has open orders.

The issue seems to be that in the filterForOpenOrdersFromSlab function, where 
  openOrders?.address.equals(new PublicKey(o.callbackInfo.slice(32))) //market.ts, line 711
  
 is called.
 The public key created from o.callbackInfo.slice(32) always results in ''11111111111111111111111111111111" - this being the toString value of the created public key.

**Comment by dr497** [comment]
Can you provide the wallet address and the market ID?

**Comment by petrucioinica99** [comment]
Market ID: wUYvayJxdPwXRFuf7E8y9LVSHuVkXhbZWNEbcE2DgTJ
Wallet address: 
DrkEjikTWi6VzeLykTaduG9hdXerjiZBMSrhEgb7mX4c 
or
6e5HM4FSHx8rUvcwdPZGEMMob5bReWn95zzUMJvAn4DU

One should have open bids, the other open asks

**Comment by dr497** [comment]
Thanks. My original fix (https://github.com/Bonfida/dex-v4/issues/88) was wrong. This commit should fix it for good https://github.com/Bonfida/dex-v4/commit/2bc9a93c715341c19c55888d2b1a9a6a32978c87. 

Thanks for your help!

**Comment by petrucioinica99** [comment]
Thanks, too! Now it works.
